### ISSUE TITLE
Not working with atmega 8

### ISSUE THREAD

**Issue by GoogleCodeExporter** [brabl2/narcoleptic#1]
```
When compiling on atmega 8 errors apears Can it be fixed?

```

Original issue reported on code.google.com by `zachw...@gmail.com` on 29 Jul 2010 at 11:20

**Comment by brabl2** [comment]
ATmega8 does not have any Interrupt triggered by Watchdog Timer (WDT).
Only System Reset can be triggered by the WDT.
So narcoleptic cannot be used on ATmega8.
