### ISSUE TITLE
PRR not declared - ArduinoIDE 1.8.1

### ISSUE THREAD

**Issue by Cysign** [brabl2/narcoleptic#12]
C:\ProgrammeKonsistent\arduino-1.8.1\libraries\narcoleptic-master\Narcoleptic.cpp: In member function 'void NarcolepticClass::disableWire()':

C:\ProgrammeKonsistent\arduino-1.8.1\libraries\narcoleptic-master\Narcoleptic.cpp:256:3: error: 'PRR' was not declared in this scope

   PRR |= _BV(PRTWI);

**Comment by vap0rtranz** [comment]
I got this same error when switching to a Yun and rebuilding.  I had not gotten the error for a Uno.  Which board are you buliding for?

**Comment by brabl2** [comment]
Hi,
The narcoleptic library is not compatible with Arduino Yun/Leonardo at this moment.
These new boards are based on ATmega32U4 chip.
According to the ATmega16U4/32U4 Datasheet this chip has not PRR register.
It has two registers PRR0 and PRR1.
All bits defined in PRR0 looks to be compatible with PRR.

So as a quick hack you can add following code to the Narcoleptic.cpp file / line 26:
```
#if !defined(PRR) && defined(PRR0)
#define PRR PRR0
#endif
```
And, please let me know if it works for you.

The PRR0 register contain PRTWI, PRTIM0, PRTIM1, PRSPI, PRADC
The PRR1 register contain PRUSB, PRTIM3, PRTIM4, PRUSART1

This is strange.
It looks that this chip does not have TIMER2 and it has only one USART, which is named USART1

All power reduction features from PRR0 register should be fully functional in narcoleptic library.
Power reduction features from PRR1 register are not supported, you can add them to the library by yourself or use some other power saving library which supports ATmega16U4/32U4.

**Comment by vap0rtranz** [comment]
I tried your code, adding PRR0 macro to my local Narcoleptic library, and yes -- it now builds against Yun.  The library also still builds against Uno with the change (so no regression).

```
/home/jupittma/Dev/arduino/arduino-1.8.3/hardware/tools/avr/bin/avr-g++" -c -g -Os  -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -MMD -flto -mmcu=atmega32u4 -DF_CPU=16000000L -DARDUINO=10803 -DARDUINO_AVR_YUN -DARDUINO_ARCH_AVR  -DUSB_VID=0x2341 -DUSB_PID=0x8041 '-DUSB_MANUFACTURER="Unknown"' '-DUSB_PRODUCT="Arduino Yun"' "-I/home/jupittma/Dev/arduino/arduino-1.8.3/hardware/arduino/avr/cores/arduino" "-I/home/jupittma/Dev/arduino/arduino-1.8.3/hardware/arduino/avr/variants/yun" "-I/home/jupittma/Dev/arduino/sketchbook/libraries/narcoleptic" "/home/jupittma/Dev/arduino/sketchbook/libraries/narcoleptic/Narcoleptic.cpp" -o "/tmp/arduino_build_227610/libraries/narcoleptic/Narcoleptic.cpp.o"
/home/jupittma/Dev/arduino/sketchbook/libraries/narcoleptic/Narcoleptic.cpp: In member function 'void NarcolepticClass::disableWire()':
/home/jupittma/Dev/arduino/sketchbook/libraries/narcoleptic/Narcoleptic.cpp:256:3: error: 'PRR' was not declared in this scope
   PRR |= _BV(PRTWI);
   ^
```

**Comment by Cysign** [comment]
I got this issue on an AtMega2560.

**Comment by brabl2** [comment]
The ATmega640/1280/1281/2560/2561 case is similar as the previous one.
It has two registers PRR0 and PRR1.
All bits defined in PRR0 looks to be compatible with PRR.
The PRR0 register contain PRTWI, PRTIM0, PRTIM1, PRTIM2, PRSPI, PRADC, PRUSART0
The PRR1 register contain PRTIM3, PRTIM4, PRTIM5, PRUSART1, PRUSART2, PRUSART3

You can also use the code from previous post.

**Comment by Cysign** [comment]
Any chance this could be automatet depending on the µC somebody is using?

**Comment by JonSilver** [comment]
I've forked doc62's improved fork of this library to my company's account in order to extend its functionality to support AVRs with PRR0 & PRR1 registers and additional peripherals like PTC. For our purposes this means the ATmega328pb. If anyone else would like to contribute mods to support other MCUs, they'd be very welcome.

**Comment by brabl2** [comment]
All PRR, PRR0 and PRR1 registers should be handled correctly now (commits c0e6853 and 61571d7).
